/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import static java.lang.String.valueOf;

/**
 *
 * @author Sondre
 */
public class mainWindowGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainWindowGUI
     */
    public mainWindowGUI() {
        initComponents();
        updateLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBank = new javax.swing.JLabel();
        jLabelIncome = new javax.swing.JLabel();
        btnBuyFarmer = new javax.swing.JButton();
        btnBuySmith = new javax.swing.JButton();
        jLabelFarmers = new javax.swing.JLabel();
        jLabelSmiths = new javax.swing.JLabel();
        jTickProgress = new javax.swing.JProgressBar();
        jLabelMorale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBank.setText("jLabel1");
        jLabelBank.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabelBankInputMethodTextChanged(evt);
            }
        });
        jLabelBank.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelBankPropertyChange(evt);
            }
        });

        jLabelIncome.setText("jLabel2");

        btnBuyFarmer.setText("Buy farmer");
        btnBuyFarmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyFarmerMouseClicked(evt);
            }
        });
        btnBuyFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyFarmerActionPerformed(evt);
            }
        });

        btnBuySmith.setText("Buy smith");
        btnBuySmith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuySmithActionPerformed(evt);
            }
        });

        jLabelFarmers.setText("jLabel1");

        jLabelSmiths.setText("jLabel1");

        jLabelMorale.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBank)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIncome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(jTickProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuySmith, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuyFarmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFarmers)
                            .addComponent(jLabelSmiths)
                            .addComponent(jLabelMorale))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBank)
                    .addComponent(btnBuyFarmer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIncome)
                        .addComponent(btnBuySmith))
                    .addComponent(jTickProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelFarmers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSmiths)
                .addGap(61, 61, 61)
                .addComponent(jLabelMorale)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyFarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyFarmerActionPerformed
        VikingRaiders.buyFarmer();
        updateLabels();
    }//GEN-LAST:event_btnBuyFarmerActionPerformed

    private void btnBuyFarmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyFarmerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyFarmerMouseClicked

    private void jLabelBankPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelBankPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabelBankPropertyChange

    private void jLabelBankInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabelBankInputMethodTextChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jLabelBankInputMethodTextChanged

    private void btnBuySmithActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuySmithActionPerformed
        VikingRaiders.buySmiths();
        updateLabels();
    }//GEN-LAST:event_btnBuySmithActionPerformed
    public void updateLabels() {
        jLabelBank.setText("Treasury:" + "  " + valueOf(VikingRaiders.getBank()));
        jLabelIncome.setText("Income:" + "  " +valueOf(VikingRaiders.getIncomeTick()));
        jLabelFarmers.setText("Number of farmers:" + "  " + valueOf(VikingRaiders.getFarmers()));
        jLabelSmiths.setText("Number of smiths:" + "  " + valueOf(VikingRaiders.getSmiths()));
        jLabelMorale.setText("Happiness of farmers (buy farmhouses to prevent it from dropping):" + VikingRaiders.getHappiness() + "/ 100");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindowGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyFarmer;
    private javax.swing.JButton btnBuySmith;
    private javax.swing.JLabel jLabelBank;
    private javax.swing.JLabel jLabelFarmers;
    private javax.swing.JLabel jLabelIncome;
    private javax.swing.JLabel jLabelMorale;
    private javax.swing.JLabel jLabelSmiths;
    private javax.swing.JProgressBar jTickProgress;
    // End of variables declaration//GEN-END:variables
}
